// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lqyhxhnlaxrkniusqjkc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxxeWh4aG5sYXhya25pdXNxamtjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcxNzAyMDgsImV4cCI6MjA2Mjc0NjIwOH0.zqK3SorrHYwt8B83DfirAlf_xH3ffvracy4jpgjAkkw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);